[build]
builder = "RAILPACK"
buildCommand = "npm run build"

[deploy]
startCommand = "cd jdi-portal && node node_modules/next/dist/bin/next start"
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 10
